name: Deploy Next.js Application

on:
  push:
    branches:
      - main
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy deployment scripts to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          passphrase: ${{ secrets.DO_SSH_PASSPHRASE }}
          source: "deploy_script.sh,environment_setup.sh"
          target: "/tmp"
          overwrite: true

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          passphrase: ${{ secrets.DO_SSH_PASSPHRASE }}
          script: |
            # Make scripts executable
            chmod +x /tmp/environment_setup.sh /tmp/deploy_script.sh

            # Run environment setup script
            /tmp/environment_setup.sh || { echo "Environment setup failed"; exit 1; }

            # Export secrets as environment variables for the deployment script
            export PROJECT_NAME="${{ secrets.PROJECT_NAME }}"
            export PROJECT_REPO="${{ secrets.PROJECT_REPO }}"
            export PROJECT_DOMAIN="${{ secrets.PROJECT_DOMAIN }}"
            export PROJECT_PORT="${{ secrets.PROJECT_PORT || '' }}"
            export PM2_FILE_TYPE="${{ secrets.PM2_FILE_TYPE || 'cjs' }}"
            export SSL_EMAIL="${{ secrets.SSL_EMAIL }}"
            export ADMIN_EMAIL="${{ secrets.ADMIN_EMAIL || '' }}"

            # Export multi-line secrets to files
            echo '${{ secrets.ENV_FILE }}' > /tmp/env_file_content
            export ENV_FILE_CONTENT=$(cat /tmp/env_file_content)

            echo '${{ secrets.PM2_ENV_VARS }}' > /tmp/pm2_env_vars
            export PM2_ENV_VARS=$(cat /tmp/pm2_env_vars)

            # Run the deployment script
            /tmp/deploy_script.sh

            # Clean up temporary files
            rm -f /tmp/env_file_content /tmp/pm2_env_vars
